spring:

  datasource:
    url: jdbc:mysql://localhost:3306/pl_review_v1
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000

  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    consumer:
      group-id: review-aggregate-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/pl-review-v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka