spring:
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

  data:
    mongodb:
      uri: mongodb://localhost:27017/pl-review-v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka