server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true

springdoc:
  api-docs:
    path: /v3/api-docs

spring:
  application:
    name: review-service
  profiles:
    active: prod
  kafka:
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    topics:
      review-created: review-created

logging:
  level:
    root: info
